### ISSUE TITLE
Remember to log out when using a browser curl etc.

### ISSUE THREAD

**Issue by brianlmerritt** [WP-API/Basic-Auth#12]
Basic Auth appears to authenticate users fine - hooray!

However, when accessing it via a browser curl tester like Rest Console or Postman, if that browser is already logged into the site (as admin for example) then the POST functions (insert post, change post etc) fail.

Not a bug per se, but a real gotcha for anyone testing the api...

**Comment by gavinr** [comment]
I have this issue too. Any ideas on ways to resolve this issue? Thanks!

**Comment by mnelson4** [comment]
merge in pull request https://github.com/eventespresso/Basic-Auth/commit/c1f070b605d3f97af9b7786ac74d04f72a19617f :) It has resolved the issue for me

**Comment by pgqueme** [comment]
Thanks for the fork @mnelson4, it worked great for me!
