### ISSUE TITLE
Make Basic-Auth part of wordpress plugins for http://wpackagist.org/

### ISSUE THREAD

**Issue by justinpage** [WP-API/Basic-Auth#20]
## Problem

http://wpackagist.org/ is modernizing how we control our plugins via composer. As such, I think it would be beneficial to allow this plugin to be downloaded from wordpress. 

I'm sure this was considered but perhaps put off due to specific needs. I just want an issue revolving around this particular subject.
## Discussion

I did circumvent the need by adding composer-installer to this module #19 . By doing so, we give control to the project owner to define where they want basic-auth to install to. That is a custom plugins folder.

**Comment by younes0** [comment]
+1
