### ISSUE TITLE
Not working since WP 4.4?

### ISSUE THREAD

**Issue by jordymeow** [WP-API/Basic-Auth#28]
Hey guys,

Just wondering if this plugin is supposed to work with WP 4.4. Seems like it has not been updated for a while, one filter has changed and by trying to debug it I feel like it is not mean to work with the latest version of WP. I might be wrong but I want to make sure. Thanks!

**Comment by danielbachhuber** [comment]
> Just wondering if this plugin is supposed to work with WP 4.4.

Yep, it works fine for me. Can you share the issue you're experiencing?

**Comment by jordymeow** [comment]
I don't use it now but basically I do this on every request:
```
$username = $_SERVER['PHP_AUTH_USER'];
$password = $_SERVER['PHP_AUTH_PW'];
$user = wp_authenticate( $username, $password );
```
And that works, I get my user and it is fine.

With the Basic Auth plugin, I know the code was slightly similar but by calling the get_current_user_id I could see that I was not properly authentified (0 was returned).

**Comment by danielbachhuber** [comment]
Ok. Hard to say what the problem was with your environment.

**Comment by jordymeow** [comment]
Yes I know :( It's simply a basic install of WordPress on my localhost using MAMP Pro, not sure why it wouldn't work but I can easily do the auth manually (per request) with the code above. It was for a quick test so I can't really spend too much time on this, was just curious if it was still supposed to work or not. I will close this as I didn't provide you any kind of debug.
