### ISSUE TITLE
discovery in index

### ISSUE THREAD

**Issue by mnelson4** [WP-API/Basic-Auth#34]
Basic Auth is mentioned as a way to authenticate on http://v2.wp-api.org/guide/authentication/, and it's mentioned that you should be able to discover what authentication methods are available on http://v2.wp-api.org/guide/discovery/.
So should the basic auth plugin add an entry into the index's "authentication" response property? It seems to me like it should (and I'm happy to make a pull request)

**Comment by rmccue** [comment]
Yeah, it probably should, although clients shouldn't actually use it. Advertising it might encourage more usage, whereas it's really only designed for development and testing.

**Comment by mnelson4** [comment]
yeah that's a good point: by adding it to the index we're encouraging automatic discovery; development and testing will generally be NON-automated. ya so probably not...
