### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by damien-mabl** [WP-API/Basic-Auth#72]
Not sure if something changed in 5.9 but this has recently died for me, anyone share the experience?  Totally silent failure, no error returned.

**Comment by AutomaticSound** [comment]
For me also...Anyone else?

**Comment by damien-mabl** [comment]
I realized that the reason mine had stopped working was a bit more nuanced.  I had a security (2fa) plugin called DoLogin Security installed on my WP instance, which had some incompatibility issues with WP 5.9.  As a result it was throwing a 500 error with absolutely no response body.  This was a fucking NIGHTMARE to debug as there was nothing in wp_debug, nothing in nginx or php logs about WHY.  

I have since stopped using the plugin (which isn't great) and can confirm the code in this repo is still working, though probably in need of a pass in general.
